// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/27/2025, 2:07:08 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/kian/ekster-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kian/ekster-website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kian/ekster-website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kian/ekster-website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kian/ekster-website/plugins/**/*.{js,ts,mjs}","/home/kian/ekster-website/composables/**/*.{js,ts,mjs}","/home/kian/ekster-website/utils/**/*.{js,ts,mjs}","/home/kian/ekster-website/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kian/ekster-website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/kian/ekster-website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/kian/ekster-website/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;