// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/12/2025, 3:08:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/kianmatton/Desktop/EksterGroepWebsite/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kianmatton/Desktop/EksterGroepWebsite/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kianmatton/Desktop/EksterGroepWebsite/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kianmatton/Desktop/EksterGroepWebsite/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kianmatton/Desktop/EksterGroepWebsite/plugins/**/*.{js,ts,mjs}","/home/kianmatton/Desktop/EksterGroepWebsite/composables/**/*.{js,ts,mjs}","/home/kianmatton/Desktop/EksterGroepWebsite/utils/**/*.{js,ts,mjs}","/home/kianmatton/Desktop/EksterGroepWebsite/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/kianmatton/Desktop/EksterGroepWebsite/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/kianmatton/Desktop/EksterGroepWebsite/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/kianmatton/Desktop/EksterGroepWebsite/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;