
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const HouseModelRig: typeof import("../components/HouseModelRig.vue")['default']
export const MobileViewportContainer: typeof import("../components/MobileViewportContainer.vue")['default']
export const ModelCarouselNav: typeof import("../components/ModelCarouselNav.vue")['default']
export const ModelPlaceholder: typeof import("../components/ModelPlaceholder.vue")['default']
export const ModelSelector: typeof import("../components/ModelSelector.vue")['default']
export const Navigation: typeof import("../components/Navigation.vue")['default']
export const WhiteCubePlaceholder: typeof import("../components/WhiteCubePlaceholder.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const AccumulativeShadows: typeof import("@tresjs/cientos")['AccumulativeShadows']
export const Align: typeof import("@tresjs/cientos")['Align']
export const AnimatedSprite: typeof import("@tresjs/cientos")['AnimatedSprite']
export const Backdrop: typeof import("@tresjs/cientos")['Backdrop']
export const BakeShadows: typeof import("@tresjs/cientos")['BakeShadows']
export const BaseCameraControls: typeof import("@tresjs/cientos")['BaseCameraControls']
export const Billboard: typeof import("@tresjs/cientos")['Billboard']
export const Bounds: typeof import("@tresjs/cientos")['Bounds']
export const Box: typeof import("@tresjs/cientos")['Box']
export const CameraControls: typeof import("@tresjs/cientos")['CameraControls']
export const CatmullRomCurve3: typeof import("@tresjs/cientos")['CatmullRomCurve3']
export const Circle: typeof import("@tresjs/cientos")['Circle']
export const CircleShadow: typeof import("@tresjs/cientos")['CircleShadow']
export const Cone: typeof import("@tresjs/cientos")['Cone']
export const ContactShadows: typeof import("@tresjs/cientos")['ContactShadows']
export const CubeCamera: typeof import("@tresjs/cientos")['CubeCamera']
export const CubicBezierLine: typeof import("@tresjs/cientos")['CubicBezierLine']
export const CustomShaderMaterial: typeof import("@tresjs/cientos")['CustomShaderMaterial']
export const Cylinder: typeof import("@tresjs/cientos")['Cylinder']
export const Dodecahedron: typeof import("@tresjs/cientos")['Dodecahedron']
export const Edges: typeof import("@tresjs/cientos")['Edges']
export const Environment: typeof import("@tresjs/cientos")['Environment']
export const FBXModel: typeof import("@tresjs/cientos")['FBXModel']
export const Fbo: typeof import("@tresjs/cientos")['Fbo']
export const Fit: typeof import("@tresjs/cientos")['Fit']
export const GLTFModel: typeof import("@tresjs/cientos")['GLTFModel']
export const GlobalAudio: typeof import("@tresjs/cientos")['GlobalAudio']
export const GradientTexture: typeof import("@tresjs/cientos")['GradientTexture']
export const Grid: typeof import("@tresjs/cientos")['Grid']
export const Helper: typeof import("@tresjs/cientos")['Helper']
export const HolographicMaterial: typeof import("@tresjs/cientos")['HolographicMaterial']
export const Html: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Icosahedron: typeof import("@tresjs/cientos")['Icosahedron']
export const Image: typeof import("@tresjs/cientos")['Image']
export const KeyboardControls: typeof import("@tresjs/cientos")['KeyboardControls']
export const LOD: typeof import("@tresjs/cientos")['LOD']
export const Lensflare: typeof import("@tresjs/cientos")['Lensflare']
export const Levioso: typeof import("@tresjs/cientos")['Levioso']
export const Lightformer: typeof import("@tresjs/cientos")['Lightformer']
export const Line2: typeof import("@tresjs/cientos")['Line2']
export const MapControls: typeof import("@tresjs/cientos")['MapControls']
export const MarchingCube: typeof import("@tresjs/cientos")['MarchingCube']
export const MarchingCubes: typeof import("@tresjs/cientos")['MarchingCubes']
export const MarchingPlane: typeof import("@tresjs/cientos")['MarchingPlane']
export const Mask: typeof import("@tresjs/cientos")['Mask']
export const MeshDiscardMaterial: typeof import("@tresjs/cientos")['MeshDiscardMaterial']
export const MeshGlassMaterial: typeof import("@tresjs/cientos")['MeshGlassMaterial']
export const MeshReflectionMaterial: typeof import("@tresjs/cientos")['MeshReflectionMaterial']
export const MeshWobbleMaterial: typeof import("@tresjs/cientos")['MeshWobbleMaterial']
export const MouseParallax: typeof import("@tresjs/cientos")['MouseParallax']
export const Ocean: typeof import("@tresjs/cientos")['Ocean']
export const Octahedron: typeof import("@tresjs/cientos")['Octahedron']
export const OrbitControls: typeof import("@tresjs/cientos")['OrbitControls']
export const Outline: typeof import("@tresjs/cientos")['Outline']
export const Plane: typeof import("@tresjs/cientos")['Plane']
export const PointMaterial: typeof import("@tresjs/cientos")['PointMaterial']
export const PointerLockControls: typeof import("@tresjs/cientos")['PointerLockControls']
export const PositionalAudio: typeof import("@tresjs/cientos")['PositionalAudio']
export const Precipitation: typeof import("@tresjs/cientos")['Precipitation']
export const QuadraticBezierLine: typeof import("@tresjs/cientos")['QuadraticBezierLine']
export const RandomizedLights: typeof import("@tresjs/cientos")['RandomizedLights']
export const Reflector: typeof import("@tresjs/cientos")['Reflector']
export const Ring: typeof import("@tresjs/cientos")['Ring']
export const RoundedBox: typeof import("@tresjs/cientos")['RoundedBox']
export const Sampler: typeof import("@tresjs/cientos")['Sampler']
export const ScreenQuad: typeof import("@tresjs/cientos")['ScreenQuad']
export const ScreenSizer: typeof import("@tresjs/cientos")['ScreenSizer']
export const ScreenSpace: typeof import("@tresjs/cientos")['ScreenSpace']
export const ScrollControls: typeof import("@tresjs/cientos")['ScrollControls']
export const Sky: typeof import("@tresjs/cientos")['Sky']
export const Smoke: typeof import("@tresjs/cientos")['Smoke']
export const SoftShadows: typeof import("@tresjs/cientos")['SoftShadows']
export const Sparkles: typeof import("@tresjs/cientos")['Sparkles']
export const Sphere: typeof import("@tresjs/cientos")['Sphere']
export const Stage: typeof import("@tresjs/cientos")['Stage']
export const Stars: typeof import("@tresjs/cientos")['Stars']
export const Stats: typeof import("@tresjs/cientos")['Stats']
export const StatsGl: typeof import("@tresjs/cientos")['StatsGl']
export const Superformula: typeof import("@tresjs/cientos")['Superformula']
export const Tetrahedron: typeof import("@tresjs/cientos")['Tetrahedron']
export const Text3D: typeof import("@tresjs/cientos")['Text3D']
export const Torus: typeof import("@tresjs/cientos")['Torus']
export const TorusKnot: typeof import("@tresjs/cientos")['TorusKnot']
export const TransformControls: typeof import("@tresjs/cientos")['TransformControls']
export const Tube: typeof import("@tresjs/cientos")['Tube']
export const UseSVG: typeof import("@tresjs/cientos")['UseSVG']
export const UseTexture: typeof import("@tresjs/cientos")['UseTexture']
export const TresLeches: typeof import("@tresjs/leches")['TresLeches']
export const ASCIIPmndrs: typeof import("@tresjs/post-processing")['ASCIIPmndrs']
export const BarrelBlurPmndrs: typeof import("@tresjs/post-processing")['BarrelBlurPmndrs']
export const BloomPmndrs: typeof import("@tresjs/post-processing")['BloomPmndrs']
export const BrightnessContrastPmndrs: typeof import("@tresjs/post-processing")['BrightnessContrastPmndrs']
export const ChromaticAberrationPmndrs: typeof import("@tresjs/post-processing")['ChromaticAberrationPmndrs']
export const ColorAveragePmndrs: typeof import("@tresjs/post-processing")['ColorAveragePmndrs']
export const ColorDepthPmndrs: typeof import("@tresjs/post-processing")['ColorDepthPmndrs']
export const DepthOfFieldPmndrs: typeof import("@tresjs/post-processing")['DepthOfFieldPmndrs']
export const DepthPickingPassPmndrs: typeof import("@tresjs/post-processing")['DepthPickingPassPmndrs']
export const DotScreenPmndrs: typeof import("@tresjs/post-processing")['DotScreenPmndrs']
export const EffectComposer: typeof import("@tresjs/post-processing")['EffectComposer']
export const EffectComposerPmndrs: typeof import("@tresjs/post-processing")['EffectComposerPmndrs']
export const FXAAPmndrs: typeof import("@tresjs/post-processing")['FXAAPmndrs']
export const FishEyePmndrs: typeof import("@tresjs/post-processing")['FishEyePmndrs']
export const Glitch: typeof import("@tresjs/post-processing")['Glitch']
export const GlitchPmndrs: typeof import("@tresjs/post-processing")['GlitchPmndrs']
export const GodRaysPmndrs: typeof import("@tresjs/post-processing")['GodRaysPmndrs']
export const GridPmndrs: typeof import("@tresjs/post-processing")['GridPmndrs']
export const Halftone: typeof import("@tresjs/post-processing")['Halftone']
export const HueSaturationPmndrs: typeof import("@tresjs/post-processing")['HueSaturationPmndrs']
export const KuwaharaPmndrs: typeof import("@tresjs/post-processing")['KuwaharaPmndrs']
export const LensDistortionPmndrs: typeof import("@tresjs/post-processing")['LensDistortionPmndrs']
export const LinocutPmndrs: typeof import("@tresjs/post-processing")['LinocutPmndrs']
export const NoisePmndrs: typeof import("@tresjs/post-processing")['NoisePmndrs']
export const OutlinePmndrs: typeof import("@tresjs/post-processing")['OutlinePmndrs']
export const Output: typeof import("@tresjs/post-processing")['Output']
export const Pixelation: typeof import("@tresjs/post-processing")['Pixelation']
export const PixelationPmndrs: typeof import("@tresjs/post-processing")['PixelationPmndrs']
export const SMAA: typeof import("@tresjs/post-processing")['SMAA']
export const SMAAPmndrs: typeof import("@tresjs/post-processing")['SMAAPmndrs']
export const ScanlinePmndrs: typeof import("@tresjs/post-processing")['ScanlinePmndrs']
export const SepiaPmndrs: typeof import("@tresjs/post-processing")['SepiaPmndrs']
export const ShockWavePmndrs: typeof import("@tresjs/post-processing")['ShockWavePmndrs']
export const TexturePmndrs: typeof import("@tresjs/post-processing")['TexturePmndrs']
export const TiltShiftPmndrs: typeof import("@tresjs/post-processing")['TiltShiftPmndrs']
export const ToneMappingPmndrs: typeof import("@tresjs/post-processing")['ToneMappingPmndrs']
export const UnrealBloom: typeof import("@tresjs/post-processing")['UnrealBloom']
export const VignettePmndrs: typeof import("@tresjs/post-processing")['VignettePmndrs']
export const TresCanvas: typeof import("../node_modules/.pnpm/@tresjs+nuxt@5.0.0_@rollup+pluginutils@5.3.0_rollup@4.52.5__esbuild@0.25.11_magicast@0._3a942d898d26f8995529a21e180e3119/node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
export const TresCanvas: typeof import("../node_modules/.pnpm/@tresjs+nuxt@5.0.0_@rollup+pluginutils@5.3.0_rollup@4.52.5__esbuild@0.25.11_magicast@0._3a942d898d26f8995529a21e180e3119/node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Body: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyHouseModelRig: LazyComponent<typeof import("../components/HouseModelRig.vue")['default']>
export const LazyMobileViewportContainer: LazyComponent<typeof import("../components/MobileViewportContainer.vue")['default']>
export const LazyModelCarouselNav: LazyComponent<typeof import("../components/ModelCarouselNav.vue")['default']>
export const LazyModelPlaceholder: LazyComponent<typeof import("../components/ModelPlaceholder.vue")['default']>
export const LazyModelSelector: LazyComponent<typeof import("../components/ModelSelector.vue")['default']>
export const LazyNavigation: LazyComponent<typeof import("../components/Navigation.vue")['default']>
export const LazyWhiteCubePlaceholder: LazyComponent<typeof import("../components/WhiteCubePlaceholder.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyAccumulativeShadows: LazyComponent<typeof import("@tresjs/cientos")['AccumulativeShadows']>
export const LazyAlign: LazyComponent<typeof import("@tresjs/cientos")['Align']>
export const LazyAnimatedSprite: LazyComponent<typeof import("@tresjs/cientos")['AnimatedSprite']>
export const LazyBackdrop: LazyComponent<typeof import("@tresjs/cientos")['Backdrop']>
export const LazyBakeShadows: LazyComponent<typeof import("@tresjs/cientos")['BakeShadows']>
export const LazyBaseCameraControls: LazyComponent<typeof import("@tresjs/cientos")['BaseCameraControls']>
export const LazyBillboard: LazyComponent<typeof import("@tresjs/cientos")['Billboard']>
export const LazyBounds: LazyComponent<typeof import("@tresjs/cientos")['Bounds']>
export const LazyBox: LazyComponent<typeof import("@tresjs/cientos")['Box']>
export const LazyCameraControls: LazyComponent<typeof import("@tresjs/cientos")['CameraControls']>
export const LazyCatmullRomCurve3: LazyComponent<typeof import("@tresjs/cientos")['CatmullRomCurve3']>
export const LazyCircle: LazyComponent<typeof import("@tresjs/cientos")['Circle']>
export const LazyCircleShadow: LazyComponent<typeof import("@tresjs/cientos")['CircleShadow']>
export const LazyCone: LazyComponent<typeof import("@tresjs/cientos")['Cone']>
export const LazyContactShadows: LazyComponent<typeof import("@tresjs/cientos")['ContactShadows']>
export const LazyCubeCamera: LazyComponent<typeof import("@tresjs/cientos")['CubeCamera']>
export const LazyCubicBezierLine: LazyComponent<typeof import("@tresjs/cientos")['CubicBezierLine']>
export const LazyCustomShaderMaterial: LazyComponent<typeof import("@tresjs/cientos")['CustomShaderMaterial']>
export const LazyCylinder: LazyComponent<typeof import("@tresjs/cientos")['Cylinder']>
export const LazyDodecahedron: LazyComponent<typeof import("@tresjs/cientos")['Dodecahedron']>
export const LazyEdges: LazyComponent<typeof import("@tresjs/cientos")['Edges']>
export const LazyEnvironment: LazyComponent<typeof import("@tresjs/cientos")['Environment']>
export const LazyFBXModel: LazyComponent<typeof import("@tresjs/cientos")['FBXModel']>
export const LazyFbo: LazyComponent<typeof import("@tresjs/cientos")['Fbo']>
export const LazyFit: LazyComponent<typeof import("@tresjs/cientos")['Fit']>
export const LazyGLTFModel: LazyComponent<typeof import("@tresjs/cientos")['GLTFModel']>
export const LazyGlobalAudio: LazyComponent<typeof import("@tresjs/cientos")['GlobalAudio']>
export const LazyGradientTexture: LazyComponent<typeof import("@tresjs/cientos")['GradientTexture']>
export const LazyGrid: LazyComponent<typeof import("@tresjs/cientos")['Grid']>
export const LazyHelper: LazyComponent<typeof import("@tresjs/cientos")['Helper']>
export const LazyHolographicMaterial: LazyComponent<typeof import("@tresjs/cientos")['HolographicMaterial']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyIcosahedron: LazyComponent<typeof import("@tresjs/cientos")['Icosahedron']>
export const LazyImage: LazyComponent<typeof import("@tresjs/cientos")['Image']>
export const LazyKeyboardControls: LazyComponent<typeof import("@tresjs/cientos")['KeyboardControls']>
export const LazyLOD: LazyComponent<typeof import("@tresjs/cientos")['LOD']>
export const LazyLensflare: LazyComponent<typeof import("@tresjs/cientos")['Lensflare']>
export const LazyLevioso: LazyComponent<typeof import("@tresjs/cientos")['Levioso']>
export const LazyLightformer: LazyComponent<typeof import("@tresjs/cientos")['Lightformer']>
export const LazyLine2: LazyComponent<typeof import("@tresjs/cientos")['Line2']>
export const LazyMapControls: LazyComponent<typeof import("@tresjs/cientos")['MapControls']>
export const LazyMarchingCube: LazyComponent<typeof import("@tresjs/cientos")['MarchingCube']>
export const LazyMarchingCubes: LazyComponent<typeof import("@tresjs/cientos")['MarchingCubes']>
export const LazyMarchingPlane: LazyComponent<typeof import("@tresjs/cientos")['MarchingPlane']>
export const LazyMask: LazyComponent<typeof import("@tresjs/cientos")['Mask']>
export const LazyMeshDiscardMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshDiscardMaterial']>
export const LazyMeshGlassMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshGlassMaterial']>
export const LazyMeshReflectionMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshReflectionMaterial']>
export const LazyMeshWobbleMaterial: LazyComponent<typeof import("@tresjs/cientos")['MeshWobbleMaterial']>
export const LazyMouseParallax: LazyComponent<typeof import("@tresjs/cientos")['MouseParallax']>
export const LazyOcean: LazyComponent<typeof import("@tresjs/cientos")['Ocean']>
export const LazyOctahedron: LazyComponent<typeof import("@tresjs/cientos")['Octahedron']>
export const LazyOrbitControls: LazyComponent<typeof import("@tresjs/cientos")['OrbitControls']>
export const LazyOutline: LazyComponent<typeof import("@tresjs/cientos")['Outline']>
export const LazyPlane: LazyComponent<typeof import("@tresjs/cientos")['Plane']>
export const LazyPointMaterial: LazyComponent<typeof import("@tresjs/cientos")['PointMaterial']>
export const LazyPointerLockControls: LazyComponent<typeof import("@tresjs/cientos")['PointerLockControls']>
export const LazyPositionalAudio: LazyComponent<typeof import("@tresjs/cientos")['PositionalAudio']>
export const LazyPrecipitation: LazyComponent<typeof import("@tresjs/cientos")['Precipitation']>
export const LazyQuadraticBezierLine: LazyComponent<typeof import("@tresjs/cientos")['QuadraticBezierLine']>
export const LazyRandomizedLights: LazyComponent<typeof import("@tresjs/cientos")['RandomizedLights']>
export const LazyReflector: LazyComponent<typeof import("@tresjs/cientos")['Reflector']>
export const LazyRing: LazyComponent<typeof import("@tresjs/cientos")['Ring']>
export const LazyRoundedBox: LazyComponent<typeof import("@tresjs/cientos")['RoundedBox']>
export const LazySampler: LazyComponent<typeof import("@tresjs/cientos")['Sampler']>
export const LazyScreenQuad: LazyComponent<typeof import("@tresjs/cientos")['ScreenQuad']>
export const LazyScreenSizer: LazyComponent<typeof import("@tresjs/cientos")['ScreenSizer']>
export const LazyScreenSpace: LazyComponent<typeof import("@tresjs/cientos")['ScreenSpace']>
export const LazyScrollControls: LazyComponent<typeof import("@tresjs/cientos")['ScrollControls']>
export const LazySky: LazyComponent<typeof import("@tresjs/cientos")['Sky']>
export const LazySmoke: LazyComponent<typeof import("@tresjs/cientos")['Smoke']>
export const LazySoftShadows: LazyComponent<typeof import("@tresjs/cientos")['SoftShadows']>
export const LazySparkles: LazyComponent<typeof import("@tresjs/cientos")['Sparkles']>
export const LazySphere: LazyComponent<typeof import("@tresjs/cientos")['Sphere']>
export const LazyStage: LazyComponent<typeof import("@tresjs/cientos")['Stage']>
export const LazyStars: LazyComponent<typeof import("@tresjs/cientos")['Stars']>
export const LazyStats: LazyComponent<typeof import("@tresjs/cientos")['Stats']>
export const LazyStatsGl: LazyComponent<typeof import("@tresjs/cientos")['StatsGl']>
export const LazySuperformula: LazyComponent<typeof import("@tresjs/cientos")['Superformula']>
export const LazyTetrahedron: LazyComponent<typeof import("@tresjs/cientos")['Tetrahedron']>
export const LazyText3D: LazyComponent<typeof import("@tresjs/cientos")['Text3D']>
export const LazyTorus: LazyComponent<typeof import("@tresjs/cientos")['Torus']>
export const LazyTorusKnot: LazyComponent<typeof import("@tresjs/cientos")['TorusKnot']>
export const LazyTransformControls: LazyComponent<typeof import("@tresjs/cientos")['TransformControls']>
export const LazyTube: LazyComponent<typeof import("@tresjs/cientos")['Tube']>
export const LazyUseSVG: LazyComponent<typeof import("@tresjs/cientos")['UseSVG']>
export const LazyUseTexture: LazyComponent<typeof import("@tresjs/cientos")['UseTexture']>
export const LazyTresLeches: LazyComponent<typeof import("@tresjs/leches")['TresLeches']>
export const LazyASCIIPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['ASCIIPmndrs']>
export const LazyBarrelBlurPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['BarrelBlurPmndrs']>
export const LazyBloomPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['BloomPmndrs']>
export const LazyBrightnessContrastPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['BrightnessContrastPmndrs']>
export const LazyChromaticAberrationPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['ChromaticAberrationPmndrs']>
export const LazyColorAveragePmndrs: LazyComponent<typeof import("@tresjs/post-processing")['ColorAveragePmndrs']>
export const LazyColorDepthPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['ColorDepthPmndrs']>
export const LazyDepthOfFieldPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['DepthOfFieldPmndrs']>
export const LazyDepthPickingPassPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['DepthPickingPassPmndrs']>
export const LazyDotScreenPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['DotScreenPmndrs']>
export const LazyEffectComposer: LazyComponent<typeof import("@tresjs/post-processing")['EffectComposer']>
export const LazyEffectComposerPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['EffectComposerPmndrs']>
export const LazyFXAAPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['FXAAPmndrs']>
export const LazyFishEyePmndrs: LazyComponent<typeof import("@tresjs/post-processing")['FishEyePmndrs']>
export const LazyGlitch: LazyComponent<typeof import("@tresjs/post-processing")['Glitch']>
export const LazyGlitchPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['GlitchPmndrs']>
export const LazyGodRaysPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['GodRaysPmndrs']>
export const LazyGridPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['GridPmndrs']>
export const LazyHalftone: LazyComponent<typeof import("@tresjs/post-processing")['Halftone']>
export const LazyHueSaturationPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['HueSaturationPmndrs']>
export const LazyKuwaharaPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['KuwaharaPmndrs']>
export const LazyLensDistortionPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['LensDistortionPmndrs']>
export const LazyLinocutPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['LinocutPmndrs']>
export const LazyNoisePmndrs: LazyComponent<typeof import("@tresjs/post-processing")['NoisePmndrs']>
export const LazyOutlinePmndrs: LazyComponent<typeof import("@tresjs/post-processing")['OutlinePmndrs']>
export const LazyOutput: LazyComponent<typeof import("@tresjs/post-processing")['Output']>
export const LazyPixelation: LazyComponent<typeof import("@tresjs/post-processing")['Pixelation']>
export const LazyPixelationPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['PixelationPmndrs']>
export const LazySMAA: LazyComponent<typeof import("@tresjs/post-processing")['SMAA']>
export const LazySMAAPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['SMAAPmndrs']>
export const LazyScanlinePmndrs: LazyComponent<typeof import("@tresjs/post-processing")['ScanlinePmndrs']>
export const LazySepiaPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['SepiaPmndrs']>
export const LazyShockWavePmndrs: LazyComponent<typeof import("@tresjs/post-processing")['ShockWavePmndrs']>
export const LazyTexturePmndrs: LazyComponent<typeof import("@tresjs/post-processing")['TexturePmndrs']>
export const LazyTiltShiftPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['TiltShiftPmndrs']>
export const LazyToneMappingPmndrs: LazyComponent<typeof import("@tresjs/post-processing")['ToneMappingPmndrs']>
export const LazyUnrealBloom: LazyComponent<typeof import("@tresjs/post-processing")['UnrealBloom']>
export const LazyVignettePmndrs: LazyComponent<typeof import("@tresjs/post-processing")['VignettePmndrs']>
export const LazyTresCanvas: LazyComponent<typeof import("../node_modules/.pnpm/@tresjs+nuxt@5.0.0_@rollup+pluginutils@5.3.0_rollup@4.52.5__esbuild@0.25.11_magicast@0._3a942d898d26f8995529a21e180e3119/node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']>
export const LazyTresCanvas: LazyComponent<typeof import("../node_modules/.pnpm/@tresjs+nuxt@5.0.0_@rollup+pluginutils@5.3.0_rollup@4.52.5__esbuild@0.25.11_magicast@0._3a942d898d26f8995529a21e180e3119/node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyBody: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.1.3_@parcel+watcher@2.5.1_@types+node@24.8.1_@vue+compiler-sfc@3.5.22_db0@0.3.4__7ae13b9cb419a8db1369d88b6c957171/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
